MarketPortal/Market/Controllers/BillingController.cs
using Market.Models;
using Market.Services.Cart;
using Market.Services.Firebase;
using Market.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Market.Services.Billing;
using Market.Data.Models;

namespace Market.Controllers
{
    [Authorize(Roles = "Organization")]
    public class BillingController : Controller
    {
        private readonly ICartService _cartService;
        private readonly IBillingService _billingService;
        private readonly IFirebaseServive _firebaseService;
        private readonly IUserService _userService;
        public BillingController(ICartService cartService, IUserService userService, IFirebaseServive firebaseService, IBillingService billingService)
        {
            _cartService = cartService;
            _userService = userService;
            _firebaseService = firebaseService;
            _billingService = billingService;
        }

        [HttpGet]
        public IActionResult Add()
        {
            BillingDetailsViewModel model = new BillingDetailsViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(BillingDetailsViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            await _billingService.CreateBillingDetailsAsync(model);
            return RedirectToAction("Index", "Cart");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            BillingDetails? model = _billingService.GetById(id);
            if (model == null)
                RedirectToAction("Add");
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(BillingDetails model)
        {
            if (!ModelState.IsValid)
                return View(model);
            await _billingService.EditBillingDetailsAsync(model);
            return RedirectToAction("Index", "Cart");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _billingService.DeleteBillingDetailsAsync(id);
            return RedirectToAction("Index", "Cart");
        }
    }
}

MarketPortal/Market/Views/Billing/Add.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model Market.Models.BillingDetailsViewModel

@{
    ViewData["Title"] = Localizer["PageTitle"];
}

<form asp-action="Add" asp-controller="Billing" method="post" class="form">
    <h2>@Localizer["Title"]</h2>

    <div class="form-container">
        <input placeholder="@Localizer["FullName"]" asp-for="FullName" class="form-control" />
        <span asp-validation-for="FullName" class="text-danger"></span>
    </div>

    <div class="form-container">
        <input placeholder="@Localizer["Address"]" asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>

    <div class="form-container">
        <input placeholder="@Localizer["City"]" asp-for="City" class="form-control" />
        <span asp-validation-for="City" class="text-danger"></span>
    </div>

    <div class="form-container">
        <input placeholder="@Localizer["PostalCode"]" asp-for="PostalCode" class="form-control" />
        <span asp-validation-for="PostalCode" class="text-danger"></span>
    </div>

    <div class="form-container">
        <input placeholder="@Localizer["PhoneNumber"]" asp-for="PhoneNumber" class="form-control" />
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
    </div>

    <div class="form-container">
        <input placeholder="@Localizer["Email"]" asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <button type="submit" class="form-submit">@Localizer["Submit"]</button>
</form>

MarketPortal/Market/Views/Billing/Edit.cshtml
@using Market.Data.Models
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model BillingDetails

@{
    ViewData["Title"] = Localizer["PageTitle"];
}

<div class ="form">
    <form asp-action="Edit" asp-controller="Billing" method="post" class="gapped">
        <h2>@Localizer["Title"]</h2>

        <div class="form-container">
            <label for="FullName">@Localizer["FullName"]</label>
            <input value="@Model.FullName" asp-for="FullName" id="FullName" class="form-control" />
            <span asp-validation-for="FullName" class="text-danger"></span>
        </div>

        <div class="form-container">
            <label for="Address">@Localizer["Address"]</label>
            <input value="@Model.Address" asp-for="Address" id="Address" class="form-control" />
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>

        <div class="form-container">
            <label for="City">@Localizer["City"]</label>
            <input value="@Model.City" asp-for="City" id="City" class="form-control" />
            <span asp-validation-for="City" class="text-danger"></span>
        </div>

        <div class="form-container">
            <label for="PostalCode">@Localizer["PostalCode"]</label>
            <input value="@Model.PostalCode" asp-for="PostalCode" id="PostalCode" class="form-control" />
            <span asp-validation-for="PostalCode" class="text-danger"></span>
        </div>

        <div class="form-container">
            <label for="PhoneNumber">@Localizer["PhoneNumber"]</label>
            <input value="@Model.PhoneNumber" asp-for="PhoneNumber" id="PhoneNumber" class="form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>

        <div class="form-container">
            <label for="Email">@Localizer["Email"]</label>
            <input value="@Model.Email" asp-for="Email" id="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>

        <div class="form-buttons">
            <button type="submit" class="form-submit">@Localizer["Submit"]</button>

        </div>
    </form>

    <form asp-action="Delete" asp-controller="Billing" method="post" onsubmit="return confirm('@Localizer["ConfirmDelete"]');" class="delete-form">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="form-submit">@Localizer["Delete"]</button>
    </form>
</div>